gideros/gideros

ios/GiderosiOSPlayer/GiderosiOSPlayer/EAGLView.m, ios/GiderosiOSPlayer/GiderosiOSPlayer/ViewController.m
Handle touch event in view controller will cause the event fired twice if the subview also handles the touch event.
eg: iAd
=> move touch event from viewcontroller to view

gdrdeamon/qtlocalpeer.cpp, player/Forms/mainwindow.ui, player/Headers/glcanvas.h, player/Headers/mainwindow.h, player/Sources/glcanvas.cpp, player/Sources/mainwindow.cpp, plugins/Microphone/source/Desktop/gmicrophone-openal.cpp
- Added Player resolutions for the iPhone 6, iPhone 6 Plus, and that
goofy 900x1200 resolution that Apple demands for iPad preview videos in
the App Store for who knows what reason.
- Added Retina support.
- Added a preprocessor directive to include unistd.h in
gmicrophone-openal.cpp on platforms other than Windows.  The reason
being that the compiler would throw an error complaining that usleep()
was undefined.
- Got a similar complaint from the compiler concerning ::getuid() in
qtlocalpeer.cpp, which went away when I added the QtLP_Private
namespace.
=> Additional Player resolutions with Retina support

2dsg/ogl.cpp, 2dsg/sprite.h
Shaders: Do not process pixels with alpha=0, to correct pure transparency problem (tkhnoman issue)
Sprite: Correct Z coordinate retrieval which was incorrectly return Y
=> 3D Stuff corrections

desktop/headers/mainwindow.h, desktop/sources/mainwindow.cpp
Canvas now scaled with 'Touch Window from Inside'
I'm new at Qt, so probably there are some weird things written.
(I still don't know how to save the resolution upon exit. Also, this code probably would be buggy if loaded from save data i think, since it detect first window size as aspect ratio)
=> Canvas Scaling fix

plugins/controller/source/Android/src/com/giderosmobile/android/plugins/controller/GControllerDefault.java
DPad controller did not work on Android TV using official gamepad -
fixed!
=> Update dpad on controller for Android TV

ui/Resources Embedded/defaultTheme.ini, ui/Resources Embedded/defaultTheme.qss, ui/mainwindow.cpp, ui/mainwindow.h, ui/mainwindow.ui, ui/textedit.cpp, ui/ui.qrc
1) UI .qss (QT StyleSheets) themes support.
2) Editor .ini themes support (QScintilla + Lua lexer + C++ lexer).
3) HTML output.
[screenshot1](https://cloud.githubusercontent.com/assets/14117468/10009842/3174df2e-60eb-11e5-8c69-d8982a840cb4.png)
[screenshot2](https://cloud.githubusercontent.com/assets/14117468/10009843/317aa184-60eb-11e5-9ff2-892c36fe5685.png)
[screenshot3](https://cloud.githubusercontent.com/assets/14117468/10009844/317eb9ae-60eb-11e5-9347-2877846d8dfe.png)
=> Theme support for Gideros Studio and HTML output.

libgid/src/qt/platform-qt.cpp
setKeepAwake probably need to be called periodically for Windows only, because it's just resetting the idle timer. 
Probably good if it is documented
=> [desktop] fix setKeepAwake

2dsg/font.cpp, 2dsg/font.h, 2dsg/fontbase.h, 2dsg/textfield.cpp, 2dsg/textfield.h, 2dsg/textfieldbase.h, 2dsg/ttbmfont.cpp, 2dsg/ttbmfont.h, 2dsg/tttextfield.cpp, 2dsg/tttextfield.h, luabinding/textfieldbinder.cpp, luabinding/textfieldbinder.h
Adds optional 'sample' parameter for TextField constructor:
`TextField.new(font, text, sample)`
`sample`: (string, optional) sample to set Y position and line height for a text.
Adds 4 new methods:
setFont(font) -- font should be either bitmap or true type font
setSample(sample) -- sample should be a string
getSample() -- returns sample string
getLineHeight() -- returns height of the sample as a number
=> textfield improvements

lua/src/lapi.c, lua/src/ldblib.c, lua/src/lstring.c, lua/src/ltable.c, lua/src/ltablib.c, lua/src/lua.h
From http://lua-users.org/wiki/LuaPowerPatches
Useful to extend Lua syntax and for some tricks.
Adds new method to `debug` library:
`debug.settypemt(type, metatable)`
Supported types: "nil","boolean","lightuserdata","number","string","table","function","userdata","thread".
For example:
```lua
-- enable string indexing (s[n]) to get character at utf8 position
string.__index = function(s, n) return utf8.sub(s, n, n) end
debug.settypemt("string", string)
local s = "Hello, world!"
print(s[8]) --> w
```
Also sets `table` library as default type metatable for all tables without user defined metatables i.e. enables following syntax: `t:insert(3); t:remove(2); t:sort(func);` etc.
=> lua type metatables powerpatch

lua/src/linit.c, lua/src/lint64.c, lua/src/lualib.h
64-bit integers as built-in Lua library registered with `int64` name. No need to require it. You have 3 ways to create int64 numbers:
```lua
#n -- from number, shortcut for int64.new(n)
int64.new(n) -- from number
int64.new(s) -- from string
```
To convert them back to Lua built-in types:
```lua
num() -- to number
num"" -- to string
```
To get and set single bits:
```lua
num[i]
num[i] = b
```
All operators are supported including new bitwise ones as for Lua double numbers.
=> int64 library

lua/src/llex.c, lua/src/llex.h, lua/src/lparser.c, lua514u/src/llex.c, lua514u/src/llex.h, lua514u/src/lparser.c
Short macro syntax:
`x @ id`
`x @ "string"`
`x @ 'string'`
`x @ [[long string]]`
`x @ -123.4`
Long macro syntax:
`x @ |any_code|`
Where you can use in place of `|` pair any pair of the following markers to define macro body:
`\ ``` ~ ! # $ % ^ & * / + = | \`
=> Lua macro implementation

2dsg/gfxbackends/Shaders.cpp, luabinding/meshbinder.cpp
Memory leaks in MeshBinder::setGenericArray() and accept FLOAT2, FLOAT3 types in ShaderProgram::updateConstant.
=> Shader leak fix 20160901

luabinding/meshbinder.cpp
Fix for calling wrong method for checking array size in MeshBinder::getColor, MeshBinder:getTextureCoordinate.
=> Fix for calling wrong method for checking array size in MeshBinder.

gdrexport/ExportCommon.cpp, gdrexport/ExportCommon.h, ui/librarytreewidget.cpp, ui/librarytreewidget.h, ui/mainwindow.cpp, ui/projectproperties.cpp, ui/projectproperties.h, ui/projectpropertiesdialog.cpp, ui/projectpropertiesdialog.ui, ui/qtutils.cpp, ui/qtutils.h, ui/ui.pro
Currently, option show all will keep all the contents of the original
image and may fill the margin with background color
Option Crop will fill the whole screen and some contents may be cropped.
Both options preserving the aspect ratio.
=> Add  scale mode options for splash image

README.md, external/liquidfun-1.0.0/liquidfun/Box2D/Box2D/Documentation/Programmers-Guide/Chapter11_Particles.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
=> Fix broken headings in Markdown files

.editorconfig
Re tabs vs spaces, I discovered that adding an .editorconfig file would stop GitHub using stupid 8 space tabs on some browsers. It doesn't work on Microsoft Edge or Internet Explorer, but works here on Firefox.
Here's a gideros repo file (without .editorconfig yet)...
https://github.com/gideros/gideros/blob/master/luabinding/box2dbinder2.cpp
... and here's the same file in my fork...
https://github.com/paul-reilly/gideros/blob/master/luabinding/box2dbinder2.cpp
=> [github] improve tab formatting on some browsers

ui/mainwindow.cpp
It didn't handle going back to maximised state before or remember maximised in between sessions. That's it fixed now.
=> [ui] Fixes toggling between maximized and fullscreen

player/Other_files/player.rc, player/player_qt5.pro
Hopefully this is a clean one. 👍 
Adds a debug_with_installed_libs config variable to the .pro file which build the player in the Build.Win directory and links against those libs. Also changes the path for the icon in the .rc file, which doesn't break the MSYS2 build script so winres must still find it.
To use the new build option, users need to create a new build configuration in Qt Creator that has "CONFIG+=debug_with_installed_libs" as an additional argument for the qmake build step.
=> Add config to win32 player.pro file to link against installed libraries

luabinding/binder.cpp
This error was the reason for me adding the C++ exclusive include paths in the win32 Makefile. But on further testing it's affecting other win32 build scripts so changing to NULL fixes it.
=> [binder] Fix 'nullptr not declared...' build errors

gdrexport/ExportBuiltin.cpp
I think this addresses #395. On export now with the optional splash screen disabled now the colour selected in Project Properties is full screen.
=> [html5] Fix background colour on export splash screen

plugins/liquidfun/source/jni/Android.mk
Fixes crash on some Android devices when using particle systems.
=> Add fp flag for ARM NEON v7 build

plugins/threads/source/luathread.cpp, plugins/threads/source/luathread.h, plugins/threads/source/threads_entry.cpp
This allows the user to set the time to wait for the thread to exit, so solves the crash when restarting problem.
=> [plugin/threads] Add configurable exit delay

samplecode-bleedingedge/Scene Manager/main.lua
little typo was causing an error when trying to call crossfade.
=> little typo + changed case for consistency

samplecode-bleedingedge/Scene Manager/scenemanager.lua
little typo was causing an error when trying to call crossFade transition in the main.lua file
local transitions = {
SceneManager.moveFromLeft,
SceneManager.moveFromRight,
SceneManager.moveFromBottom,
SceneManager.moveFromTop,
SceneManager.moveFromLeftWithFade,
SceneManager.moveFromRightWithFade,
SceneManager.moveFromBottomWithFade,
SceneManager.moveFromTopWithFade,
SceneManager.overFromLeft,
SceneManager.overFromRight,
SceneManager.overFromBottom,
SceneManager.overFromTop,
SceneManager.overFromLeftWithFade,
SceneManager.overFromRightWithFade,
SceneManager.overFromBottomWithFade,
SceneManager.overFromTopWithFade,
SceneManager.fade,
SceneManager.crossFade,
SceneManager.flip,
SceneManager.flipWithFade,
SceneManager.flipWithShade,
}
=> little typo was causing an error

plugins/create-wiki-pages.lua
Please remove all language tags from this tool.
Reasons:
- nobody can translate the whole wiki
- when we consult the wiki in a language other than english, the wiki is missing a lot of documentation
- it's hard to use the wiki to translate using t1, t2, t3, ... tags. Especially when we add new content
- ...
Please remove those language tags!
Thank you.
=> please remove all language tags

plugins/imgui/source/Common/imgui_bindings.cpp, plugins/imgui/source/Common/imgui_src/imconfig.h, plugins/imgui/source/Common/imgui_src/imgui.cpp, plugins/imgui/source/Common/imgui_src/imgui.h, plugins/imgui/source/Common/imgui_src/imgui_demo.cpp, plugins/imgui/source/Common/imgui_src/imgui_draw.cpp, plugins/imgui/source/Common/imgui_src/imgui_internal.h, plugins/imgui/source/Common/imgui_src/imgui_tables.cpp, plugins/imgui/source/Common/imgui_src/imgui_widgets.cpp, plugins/imgui/source/Common/imgui_user.cpp, plugins/imgui/source/Common/imgui_user.h
[plugin/imgui] Added InputText callback functions
[plugin/imgui] Added new IO functions
[plugin/imgui] Added new CTX functions
[plugin/imgui] Changed ImGui:newFrame(dt)
[plugin/imgui] Removed ImGui:setAutoUpdateCursor(flag)
[plugin/imgui] Fixed texture memory leaks
[plugin/imgui] Fixed shared FontAtlas crush
[plugin/imgui] Fixed ImGui:setNextWindowSizeConstraints()
[plugin/imgui] Fixed ImGui:tableSetupScrollFreeze(cols, rows)
=> ImGui Update

scripts/GidQtLinux.mk
* Fixes tls/lib typo
* Fixes copying old lua path lines
* We need this line
* -cd plugins; git archive $(CURRENT_GIT_BRANCH) | tar -x -C ../$(RELEASE)/All\ Plugins
All Plugins is necessary with Lua plugins and exports need some of them that work with from copied winbuild_Templates for now
=> [Linux build fixes]

android/GiderosAndroidPlayer/app/src/main/java/com/giderosmobile/android/player/GiderosApplication.java, android/lib/jni/gideros.cpp, emscripten/main.cpp, emscripten/platform-js.cpp, ios/iosplayer/iosplayer/giderosapi.mm, libgid/include/gapplication.h, libgid/include/platform.h, libgid/src/android/platform-android.cpp, libgid/src/pi/platform-pi.cpp, libgid/src/qt/platform-qt.cpp, libgid/src/win32/platform-win32.cpp, libgid/src/winrt/platform-winrt.cpp, libgideros/event.h, luabinding/applicationbinder.cpp, luabinding/eventdispatcherbinder.cpp, luabinding/luaapplication.cpp
I almost get win32 openFileDialog working :-(
- set title **OK**
- set start directory **OK**
- filter extensions **NOT OK** :-(
You use the usual `application:get("openFileDialog", "Title|startdir|Text (*.txt);; Image (*.png)")`. A sample code:
--	local picdir = application:get("directory", "pictures") -- result C:\Users\xxx\Pictures
local picdir = "c:\\tmp" -- "C:/tmp/" -> old format is not working!
local path = application:get("openFileDialog", "My Title|"..picdir.."|Text (*.txt);; Image (*.png)")
Compiled and tested with the latest hgy29 commit on my windows 10 machine. I tried following coding style as much as I could. Hope this helps?
[platform-win32.zip](https://github.com/gideros/gideros/files/9884948/platform-win32.zip)
=> [win32] implementing openFileDialog

libgid/src/win32/platform-win32.cpp
fix win32 openDirectoryDialog (needed 3 arguments, now works with 2 arguments)
Tested on win32 export:
-- local path = application:get("openDirectoryDialog", "Pick a folder", g_currdir, "put here for bug") -- "title", "path", "bug" CURRENT GIDEROS
local path = application:get("openDirectoryDialog", "Pick a folder", g_currdir) -- "title", "path" OK
--local path = application:get("openDirectoryDialog", "Pick a folder") -- "title", "path" OK (doesn't crash the app)
Thank you 😄
=> win32 openDirectoryDialog

ui/plugineditor.ui
When you add the Require plugin and go to its properties, when you hover with the mouse an option checkbox, the horizontal scroll bar jumps to the right and option text becomes unreadable.
So I propose to increase the window width quite a bit.
Thank you :-)
=> Plugins Require Window size too small

Library/3dbase/3DGdxLoader.lua
In G3DFormat.lua we use setColorTransform() based on mtl.kd:
-- COLOR
if mtl.kd then m:setColorTransform(mtl.kd[1], mtl.kd[2], mtl.kd[3], mtl.kd[4]) end
The problem is fbx (json) was missing its alpha value mtl.kd[4] which would crash the app.
=> missing alpha value for fbx (json) models

libgid/src/win32/platform-win32.cpp, win32_example/win32.cpp
My issue was in win32 when a key modifier was being pressed (SHIFT, ALT, CTRL) it wouldn't get released when no longer pressed (it was like stuck in the pressed state). To cancel the pressed state one had to press the modifier key again!
I changed according to your recommandation and now using _if (GetKeyState(VK_xxx) & 0x8000)_
I also added _& 0x8000_ to **int getKeyboardModifiers()** but I kept the GetAsyncKeyState otherwise the modifiers wouldn't work with the mouse.
I tested and this looks good to me with many shortcut keys (NUMPAD, F1->F12, PAGE_UP, PAGE_DOWN, ...)
Thank you 🛩️
=> sticky modifier keys
