gideros/gideros

- .gitignore
- ignore more building results and intermediate files from QT Creator and Visual Studio
> More gitignore

- libpreviewwidget/previewwidget.cpp
- Auto fit image inside preview area
- Show image size label on lower left corner
- Show file path for non-image asset
> Minor improvement on Preview Widget

- luabinding/spritebinder.cpp
- luabinding/spritebinder.h
Bound the existing swapChildrenAt to enable faster swapping of sprites.
> Binded swapChildrenAt

- .gitignore
- player/Sources/glcanvas.cpp
Fixing orientation on desktop version!
> Orientation Fix

- desktop/sources/mainwindow.cpp
forgotten line from last commit
> [desktop] setWindowSize fix

- desktop/headers/mainwindow.h
- desktop/sources/mainwindow.cpp
The one that checked is at properties.bin (not at application:setScaleMode)
> [desktop] check Scale Mode

- desktop/headers/mainwindow.h
- desktop/sources/mainwindow.cpp
- libgid/src/qt/platform-qt.cpp
Should be able to fix issue #132 and #134 
Sorry for this, and thanks for rechecking the code :)
> [desktop] removed automated pos & size

- libgid/src/qt/platform-qt.cpp
- player/Sources/glcanvas.cpp
- plugins/controller/source/controller.cpp
- plugins/controller/source/controller.h
- plugins/controller/source/controllerbinder.cpp
- plugins/controller/source/gcontroller.cpp
- plugins/controller/source/gcontroller.h
Button now also have realCode.
A new event is also generated, Event.AXIS_JOYSTICK which contain "axis"
and "strength".
This made possible button mapping on any controller vendor.
> [Controller] handle realCode and unknown axis

- libgid/include/qt/ginput-qt.h
- libgid/src/android/ginput-android.cpp
- libgid/src/ios/ginput-ios.mm
- libgid/src/qt/ginput-qt.cpp
- libgid/src/win32/ginput-win32.cpp
- libgid/src/winrt/ginput-winrt.cpp
- luabinding/eventdispatcherbinder.cpp
- player/Sources/glcanvas.cpp
Haven't check with the new version yet.
> [gideros] touch pressure & type

- libgid/src/android/platform-android.cpp
- libgid/src/ios/platform-ios.mm
- libgid/src/qt/platform-qt.cpp
- libgid/src/win32/platform-win32.cpp
- libgid/src/winrt/platform-winrt.cpp
- luabinding/applicationbinder.cpp
Rearrange and add more method to application:set/get
> [qt] application:set/get new method

- plugins/notification/source/iOS/ExampleAppDelegate.m
- plugins/notification/source/iOS/Plugins/Notification/NotificationClass.mm
- plugins/notification/source/iOS/install.html
Update notification plugin for ios.
> PLUGINS: Update notifications plugin for ios 8+.

- ui/mainwindow.cpp
> Fix for print ?? of Korean characters in IDE "Find in files" result.

- 2dsg/gmesh.cpp
GMesh::resizeColorArray bug fixed. Clearing code fixed also.
> Mesh color array fix 20160901

- ui/mainwindow.cpp
- ui/mainwindow.h
- ui/mdiarea.cpp
- ui/mdiarea.h
- ui/textedit.cpp
- ui/textedit.h
Enable Gideros Studio code editor to change tab by keyboard ctrl+tab on windows system.
> Tab switching by ctrl+tab key on Windows system.

- luabinding/box2dbinder2.cpp
- luabinding/box2dbinder2.h
Added liquidfun's Particle contact callback binding.
Add binding b2ParticleSystem_getParticleGroupList, b2ParticleGroup_destroyParticles, b2ParticleGroup_getParticleCount, b2ParticleGroup_containsParticle.
> Liquidfun binding ex 20160901

- libgid/src/platformutil.cpp
- player/Sources/main.cpp
The two commits fixes "Wrong frame rate - linux/pi #206" bug and includes plugins for Linux
> fix #206 and activation plugins for Linux

- plugins/storekit/source/iOS/storekit.mm
Add a currencyString to display the locale price.
> Add a currencyString to display the locale price.

- plugins/gmedia/source/media.cpp
- plugins/gmedia/source/media.h
- plugins/gmedia/source/mediabinder.cpp
i could not check if it works, as i don't know how to build gideros nor plugins.
i have tried to imitate existing functions getPicture and savePicture, without understanding completely where what happens, so please check or test thoroughly.
> add getFile and saveFile methods for desktop

- doc/reference/gideros/KeyCode/R.html
- docsrc/KeyCode.xml
Reordered nums and letters, checked their keycode and added entries if missing.
> KeyCode update

- ui/mainwindow.cpp
- ui/mainwindow.h
- ui/mainwindow.ui
Sorry, that last PR had a line in it that shouldn't have been changed. Here's a cleaner one.
> [ui] Add fullscreen mode (Settings/F11)

- luabinding/binder.cpp
- luabinding/binder.h
I can resubmit this without the tidy if you like but in an ideal world I'd like to see touched files get a spring clean for consistent alignment etc.
> Binder - add more direct createClass method (plus tidy)

- plugins/create-wiki-pages.lua
- plugins/vogon.wiki.lua
Sorry, just a quick adjustment.
> [docs] Update create-wiki-docs to add examples for consts and events

- plugins/create-wiki-pages.lua
- plugins/vogon.wiki.lua
Just an update after seeing that the Threads docs class link was wrong on the wiki. Can now have "Threads" as a plugin/feature and not a class.
> [wikidocgen] Support landing page and multiple classes

- gdrexport/main.cpp
- ui/mainwindow.cpp
This now allows us to require from subdirectories with Lua plugins.
> [luaplugins] Allow subdirectories in lua plugins

- ui/textedit.cpp
Enables scintilla multi-line typing and multi-cursor editing.
> [studio] Add multi-cursor editing

- plugins/threads/source/StateToState.cpp
- plugins/threads/source/jni/Android.mk
- plugins/threads/source/luathread.cpp
- plugins/threads/source/luathread.h
- plugins/threads/source/threads.pro
- plugins/threads/source/threads_entry.cpp
- plugins/threads/source/threadtimedluahook.cpp
- plugins/threads/source/threadtimedluahook.h
- plugins/threads/source/win32/Makefile
- plugins/threads/source/winrt/threads/threads.Shared/threads.Shared.vcxitems
- plugins/threads/source/winrt/threads/threads.Shared/threads.Shared.vcxitems.filters
- plugins/threads/source/winrt/threads/threads.Windows/threads.Windows.vcxproj
- plugins/threads/source/winrt/threads/threads.WindowsPhone/threads.WindowsPhone.vcxproj
- plugins/threads/threads.gplugin
Doesn't crash on replay anymore in player with Studio. Tested on Win Desktop export and Android. 
Btw the commit age is from the oldest commit everything was squashed into.
> [plugin/threads] Add luasocket, lfs and json.

- doc/file_system.html
See http://forum.giderosmobile.com/discussion/comment/62823/#Comment_62823
> main, init rules are top level directory only

- plugins/imgui/source/Android/jni/Android.mk
- plugins/imgui/source/Common/imgui_bindings.cpp
- plugins/imgui/source/Desktop/imgui.pro
- plugins/imgui/source/emscripten/Makefile
- plugins/imgui/source/win32/Makefile
ImGui:text(string) now uses 'ImGui::TextUnformated(text)' since we can format string from LUA, and its faster.
And a bit of code refactoring :)
> [plugin/imgui] touch support

- .gitignore
Just adding some paths to .gitignore.
> Ignore .xmake, .vscode and Build.PLAT dirs

- plugins/imgui/source/Common/imgui_bindings.cpp
- plugins/imgui/source/Common/imgui_src/imconfig.h
- plugins/imgui/source/Common/imgui_user.cpp
- plugins/imgui/source/Common/imgui_user.h
+ Added new IO functions to reset ImGui state (keys and mouse).
+ Changed ImGui:newFrame(event) to ImGui:newFrame(dt)
> ImGui update

- 2dsg/sprite.cpp
- luabinding/spritebinder.cpp
- luabinding/texturebasebinder.cpp
- luabinding/texturebasebinder.h
- plugins/bump/source/bump.cpp
- plugins/imgui/source/Common/imgui_bindings.cpp
- plugins/imgui/source/Common/imgui_src/imconfig.h
- plugins/imgui/source/Common/imgui_src/imgui.cpp
- plugins/imgui/source/Common/imgui_src/imgui.h
- plugins/imgui/source/Common/imgui_src/imgui_demo.cpp
- plugins/imgui/source/Common/imgui_src/imgui_draw.cpp
- plugins/imgui/source/Common/imgui_src/imgui_internal.h
- plugins/imgui/source/Common/imgui_src/imgui_tables.cpp
- plugins/imgui/source/Common/imgui_src/imgui_widgets.cpp
- plugins/imgui/source/Common/imgui_src/imstb_rectpack.h
- plugins/imgui/source/Common/imgui_src/imstb_textedit.h
- plugins/imgui/source/Common/imgui_src/imstb_truetype.h
Not related to this update:
```[plugin/imgui] Better way to detect modifiers keys (ALT, CTRL, SHIFT, META (SUPER))```
I had old version of my own binding on my home pc, because I forgot to grab latest version from my github page :smile:
> ImGui update & other changes

- Library/3dbase/3DGdxLoader.lua
- Library/3dbase/3DObjLoader.lua
- Library/3dbase/3DShapes.lua
- Library/3dbase/3DView.lua
- Library/3dbase/G3DFormat.lua
- Library/3dbase/gltf.lua
- samplecode/Graphics3D/3D-Anim/3D-Anim.gproj
- samplecode/Graphics3D/3D-Anim/assets/main.lua
update with android fix:
- before .glb models worked on android but only when model had only vertex color (tested with occulus gideros sample)
- now .glb models also work when they embed an image texture (only diffuse image texture for now, may add normal map texture when possible)
This fix should also apply for linux (waiting for feedback from hito9) and other os.
PS: this time I setup the folders accordingly so links to the Library should be correct with the ../../.. stuff :-)
PS2: oh 1 mistake I did here :-(
--Unit Sphere
local Sphere=Core.class(Mesh3D)
function Sphere:init(**radius,steps**)
Those should be (steps,radius) I wanted to change the order which is more logical imho but I thought about other samples calling the Sphere class and decided to leave it as is but somehow I forgot …
> update to Library/3dbase with android (and probably linux and other os) fix

- iconlibrary/iconlibrary.cpp
- ui/Resources/start/examples.xml
- ui/finddialog.cpp
- ui/finddialog.h
- ui/finddialog.ui
- ui/findreplacedialog.cpp
- ui/findreplacedialog.h
- ui/gotolinedialog.cpp
- ui/mainwindow.cpp
- ui/mainwindow.h
- ui/mainwindow.ui
- ui/preferencesdialog.cpp
- ui/preferencesdialog.h
- ui/preferencesdialog.ui
- ui/replacedialog.cpp
- ui/replacedialog.h
- ui/textedit.cpp
- ui/textedit.h
- ui/ui.pro
[Studio] Color Picker (view/insert a color syntax into cursor position)
[Studio] Wrap/Unwrap line in the current page if needed
[Studio] "Append toolbar to menu" option (Preferences checkbox)
[Studio] Texture Packer / Font Creator menu entries (Tools Menu)
[Studio] Auto paste selected text to Find/Replace dialog box
[Studio] Fix "Go To Line" function
[Studio] Fix "Find/Replace" function in the very first line
[Studio] Fix "Replace All" words behaviour for all lines
[Studio] Modified "Find Dialog" for Next/Previous search
Can you delete debug option in ui.pro file, I forgot sorry :) It is good to be cautious about all changes.  There may be more suitable methods.
> [Studio] Preview pic for GTween example

- samplecode/Collision/CuteC2/assets/Scenes/BaseScene.lua
- samplecode/Collision/CuteC2/assets/Scenes/Collisions.lua
- samplecode/Collision/CuteC2/assets/Scenes/GJK.lua
- samplecode/Collision/CuteC2/assets/Scenes/Rays.lua
- samplecode/Collision/CuteC2/assets/Scenes/TOI.lua
- samplecode/Collision/CuteC2/assets/Shapes/Poly.lua
- samplecode/Collision/CuteC2/assets/main.lua
Removed non existent call to ImGui function "shutdown"
The number of shapes on the "Ray" scene has been reduced to 16
Changed application background color to dark gray 
The selected theme is now saved when switching to another scene
Fixed "Poly" properties window not showing "Draw BBOX" checkbox
> Cute_c2 demo updted

- libgid/src/qt/platform-qt.cpp
- libgid/src/win32/platform-win32.cpp
- win32_example/win32.cpp
platform-win32.cpp:
- getKeyboardModifiers were still activated after keyup events: fixed
win32.cpp:
- mouse wheel had a * 120 which resulted in delta of 14400 (120 * 120): fixed
> various win32 fixes

- libgid/src/win32/platform-win32.cpp
File platform-win32.cpp:
- pathfileexists test if a folder or a file exists + can test for modes: 0=Existence only, 2=Write-only, 4=Read-only, 6=Read and write returns 1 on success or nil on fail
- I tried to set cursor (arrow, upArrow, cross, ...), the code works (doesn't crash) but the mouse cursor doesn't change. I leave the code as is (not urgent for now!?)
> I forgot pathfileexists for win32 in previous commit :-(

- Library/3dbase/3DObjLoader.lua
Using Luau String split function is 8x faster than home made Split function.
> use Luau internal string:split function

- Library/ui/uilayout.lua
- Library/ui/uiselection.lua
Just fixing some typos:
--!NEEDS:uinit.lua
to
--!NEEDS:uiinit.lua
I don't really know if they are actually needed but fixing them just in case 🐙
> ui Library typos
